### ISSUE TITLE
there  is bug on android api 15,but wok on api 22  is ok in my app. 

### ISSUE THREAD

**Issue by lengxf** [android10/frodo#28] opened 2016-04-25 03:21 UTC
Caused by: java.lang.NullPointerException
                                                                       at com.fernandocejas.frodo.aspect.LogObservable.methodAnnotatedWithRxLogObservable(LogObservable.java:27)
                                                                       at com.jytcorp.ingot.data.sqlite.dataset.AccountTable.getDefaultUser(AccountTable.java)
                                                                       at com.jytcorp.ingot.data.sqlite.IngotDB.getDefaultUser(IngotDB.java:38)
                                                                       at com.jytcorp.ingot.data.DataServiceProvider.getUser(DataServiceProvider.java:62)
                                                                       at com.jytcorp.ingot.domain.manager.UserManager.getUser(UserManager.java:19)

**Comment by lengxf** [comment] 2016-04-25 03:22
https://github.com/lengxf/Ingot
this is my demo.

**Comment by android10** [comment] 2016-05-22 11:18
This should be fixed within version 0.8.3. 😃 . I'm gonna close it and let's re open whether the issue is not fixed within the latest version.

**Closed by android10** 2016-05-22 11:18 UTC
